=== qgis-deployment/qgis-deployment-toolbelt-cli/docs/schemas/profile/qgis_profile.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/qgis-deployment/qgis-deployment-toolbelt-cli/raw/main/docs/schemas/profile/qgis_profile.json",
    "$comment": "A QGIS profile described in a JSON file in the QDT formalism.",
    "type": "object",
    "properties": {
        "alias": {
            "description": "Profile's name in an human readable form, allowing special characters.",
            "type": "string"
        },
        "author": {
            "description": "Name of profile author and maintainer.",
            "type": "string"
        },
        "description": {
            "description": "Profile description.",
            "type": "string"
        },
        "email": {
            "description": "Email of profile's author and maintainer.",
            "format": "email",
            "maxLength": 127,
            "minLength": 6,
            "type": "string"
        },
        "folder_name": {
            "description": "Name of the profile's directory in QGIS.",
            "type": "string"
        },
        "icon": {
            "description": "Relative path to the icon used for shortcuts.",
            "type": "string"
        },
        "name": {
            "description": "Profile name without any special characters.",
            "type": "string"
        },
        "qdtMinVersion": {
            "description": "Minimum version of QGIS Deployment Toolbelt required to deploy this profile. Must follow Semver. If the running QDT version is older, the profile is not deployed.",
            "type": "string",
            "pattern": "^[0-9]+\\.[0-9]+\\.[0-9]+$",
            "examples": [
                "0.45.0"
            ]
        },
        "plugins": {
            "description": "Plugins installed with the profile.",
            "title": "QGIS Plugins",
            "type": "array",
            "items": {
                "$ref": "qgis_plugin.json"
            }
        },
        "qgisMaximumVersion": {
            "description": "Maximum QGIS version where the profile can be deployed. It should complies with SemVer.",
            "maxLength": 14,
            "minLength": 5,
            "pattern": "^(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)$",
            "type": "string"
        },
        "qgisMinimumVersion": {
            "description": "Minimum QGIS version where the profile can be deployed. It should complies with SemVer.",
            "maxLength": 14,
            "minLength": 5,
            "pattern": "^(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)$",
            "type": "string"
        },
        "rules": {
            "description": "Logical rules based on contextual elements that condition profile deployment.",
            "title": "QGIS Plugins",
            "type": "array",
            "items": {
                "$ref": "rules.json"
            }
        },
        "splash": {
            "description": "Relative path to the splash image.",
            "type": "string"
        },
        "version": {
            "description": "Profile version. Must complies with SemVer.",
            "maxLength": 14,
            "minLength": 5,
            "pattern": "^(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)$",
            "type": "string"
        }
    },
    "required": [
        "author",
        "email",
        "name",
        "version"
    ]
}

=== qgis-deployment/qgis-deployment-toolbelt-cli/examples/profiles/demo/profile.json
{
  "$schema": "https://raw.githubusercontent.com/qgis-deployment/qgis-deployment-toolbelt-cli/main/docs/schemas/profile/qgis_profile.json",
  "name": "qdt_demo",
  "folder_name": "demo",
  "description": "Demo QGIS profile for QDT.",
  "author": "Julien Moura",
  "email": "infos+qdt@oslandia.com",
  "icon": "images/icon_shortcut_qdt_demo.ico",
  "qdtMinVersion": "0.35.0",
  "qgisMinimumVersion": "3.28.0",
  "qgisMaximumVersion": "4.99.15",
  "version": "1.1.0",
  "plugins": [
    {
      "folder_name": "profile_manager",
      "name": "Profile Manager",
      "official_repository": true,
      "plugin_id": 3547,
      "version": "0.7.4"
    }
  ]
}

=== qgis-deployment/qgis-deployment-toolbelt-cli/examples/profiles/only_linux/profile.json
{
  "$schema": "https://raw.githubusercontent.com/qgis-deployment/qgis-deployment-toolbelt-cli/main/docs/schemas/profile/qgis_profile.json",
  "name": "QDT Only Linux",
  "folder_name": "qdt_only_linux",
  "description": "Demonstrating a QDT profile that's deployed only on Linux.",
  "author": "Julien Moura",
  "email": "infos+qdt@oslandia.com",
  "qdtMinVersion": "0.41.0",
  "qgisMinimumVersion": "3.34.0",
  "qgisMaximumVersion": "4.10.10",
  "version": "1.0.0",
  "rules": [
    {
      "name": "Environment",
      "description": "Profile is configured to run only on Linux.",
      "conditions": {
        "all": [
          {
            "path": "$.environment.operating_system_code",
            "value": "linux",
            "operator": "equal"
          },
          {
            "path": "$.date.current_year",
            "value": 2023,
            "operator": "greater_than_inclusive"
          }
        ]
      }
    }
  ]
}

=== qgis-deployment/qgis-deployment-toolbelt-cli/tests/fixtures/profiles/good_profile_complete.json
{
  "$schema": "../../../docs/schemas/profile/qgis_profile.json",
  "name": "qdt_test_profile_complete",
  "alias": "Conférence QGIS FR",
  "description": "Profil de démonstration de la gestion des profils QGIS par Oslandia (atelier des journées QGIS FR 2022).",
  "author": "Benoît Ducarouge et Julien Moura",
  "email": "qgis@oslandia.com",
  "icon": "images/qgis_icon.ico",
  "splash": "images/splash_qgis-fr_600x287.png",
  "qgisMinimumVersion": "3.22",
  "qgisMaximumVersion": "3.30",
  "version": "1.1.0",
  "plugins": [
    {
      "name": "french_locator_filter",
      "version": "1.0.4",
      "url": "https://plugins.qgis.org/plugins/french_locator_filter/version/1.0.4/download/",
      "location": "remote",
      "plugin_id": 1846,
      "upgrade_mode": "delete"
    },
    {
      "name": "pg_metadata",
      "version": "1.2.1",
      "url": "https://plugins.qgis.org/plugins/pg_metadata/version/1.2.1/download/",
      "location": "remote",
      "upgrade_mode": "keep"
    },
    {
      "name": "Layers menu from project",
      "version": "2.1.0",
      "official_repository": true,
      "plugin_id": 0,
      "location": "remote"
    },
    {
      "name": "Geotuileur",
      "version": "1.0.0",
      "url": "https://oslandia.gitlab.io/qgis/ign-geotuileur/geotuileur.1.0.0.zip",
      "location": "remote",
      "official_repository": false,
      "repository_url_xml": "https://oslandia.gitlab.io/qgis/ign-geotuileur/plugins.xml"
    }
  ]
}

=== qgis-deployment/qgis-deployment-toolbelt-cli/examples/profiles/Viewer Mode/profile.json
{
  "$schema": "https://raw.githubusercontent.com/qgis-deployment/qgis-deployment-toolbelt-cli/main/docs/schemas/profile/qgis_profile.json",
  "name": "QDT Viewer Mode",
  "folder_name": "qdt_viewer_mode",
  "description": "Demo QGIS profile for QDT customized for end-users which are only viewers.",
  "author": "Julien Moura",
  "email": "infos+qdt@oslandia.com",
  "icon": "images/icon_shortcut_qdt_viewer_mode.ico",
  "qdtMinVersion": "0.35.0",
  "qgisMinimumVersion": "3.34.4",
  "qgisMaximumVersion": "4.99.15",
  "version": "1.1.2",
  "plugins": [
    {
      "name": "Layers menu from project",
      "folder_name": "menu_from_project",
      "official_repository": true,
      "plugin_id": 43,
      "version": "2.4.4"
    },
    {
      "name": "qNote",
      "folder_name": "qNote",
      "official_repository": true,
      "plugin_id": 122,
      "version": "2.3"
    },
    {
      "name": "QuickMapServices",
      "folder_name": "quick_map_services",
      "official_repository": true,
      "plugin_id": 666,
      "version": "0.19.33"
    },
    {
      "name": "QuickOSM",
      "folder_name": "QuickOSM",
      "official_repository": true,
      "plugin_id": 579,
      "upgrade_mode": "keep",
      "version": "2.2.3"
    },
    {
      "name": "Red Layer",
      "folder_name": "redLayer",
      "official_repository": true,
      "plugin_id": 752,
      "upgrade_mode": "delete",
      "version": "2.2"
    },
    {
      "name": "Spreadsheet Layers",
      "folder_name": "SpreadsheetLayers",
      "official_repository": true,
      "plugin_id": 766,
      "version": "2.1.0"
    }
  ]
}
